### PR TITLE
MMB: Capitalize passenger titles

### LINKED ISSUE #667: App crashes when going to manage my booking detail screen
IMG_63B7995C025E-1

### PR DESCRIPTION
**Pull request by tbergq**
From current mmb, we get titles as lowercase.
Passenger title enum expects title to be capitalized.

closes #667

### CODE REVIEW

File: apps/graphql/src/apps/manageMyBooking/dataloaders/Bookings.js [hunk 1]
```diff
@@ -51,6 +53,8 @@ export const sanitizeBooking = (booking: BookingApiResult) => {
 
 const sanitizePassengers = (booking: BookingApiResult): Array<Passenger> =>
   booking.passengers.map(passenger => {
+    const passengerTitle = capitalize(passenger.title);
+    const title: PassengerTitle = (passengerTitle: any);
```
Comment (JoseDuSV) [inline apps/graphql/src/apps/manageMyBooking/dataloaders/Bookings.js]: It will be nice to get rid of this part, but for now I don't really have anything better 😄. And since we are just working with mocked data for now it doesn't make much sense to dig deeper into response types when it will be updated once/if we connect MMB to real endpoint.
