### PR TITLE
Fix RangeDatePicker arrow sync on iOS

### LINKED ISSUE #639: Fix arrow animation in RangeDatePicker
Animation is desynchronised after selection. When arrow is clicked both animations should be restarted.

### PR DESCRIPTION
**Pull request by jvaclavik**
On iOS was still some problem with sync, now it should be fine.
(Fixes #639)

### CODE REVIEW

File: packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js [hunk 1]
```diff
@@ -34,35 +34,48 @@ const RenderArrows = ({ scale }) => (
...
-      }),
-    ]).start(() => {
-      if (AnimatedDayItemArrow.animating) {
+    if (AnimatedDayItemArrow.scale === undefined) {
+      AnimatedDayItemArrow.scale = new Animated.Value(0);
+    }
+    if (
+      AnimatedDayItemArrow.scale &&
+      AnimatedDayItemArrow.scale._value === 0 &&
+      AnimatedDayItemArrow.numberOfInstances !== 0
```
Comment (JoseDuSV) [inline packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js]: Animation freezes when picker is opened for second time. It looks like because of this condition.
anim-freeze

File: packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js [hunk 2]
```diff
@@ -34,35 +34,48 @@ const RenderArrows = ({ scale }) => (
...
-      }
-    });
+      });
+    }
   }
 
   componentDidMount() {
-    AnimatedDayItemArrow.animating = true;
-    AnimatedDayItemArrow.handleAnimation();
+    if (!AnimatedDayItemArrow.animating) {
```
Comment (JoseDuSV) [inline packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js]: I think that those conditions and `animating`-`numberOfInstances` combinations starting to be quite complex and slightly hard to read.

Cannot we just simply stop/hide animation when user is touching/dragging picker elements and start it again when he stops. I think it's done in similar way in current Kiwi mobile app.

File: packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js [hunk 3]
```diff
@@ -34,35 +34,56 @@ const RenderArrows = ({ scale }) => (
...
+          AnimatedDayItemArrow.handleAnimation();
+        }
+      });
+    }
   }
 
   componentDidMount() {
-    AnimatedDayItemArrow.animating = true;
-    AnimatedDayItemArrow.handleAnimation();
+    if (AnimatedDayItemArrow.numberOfInstances === undefined) {
```
Comment (JoseDuSV) [inline packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js]: Definitely looks better now. Can't say I like all those conditions, but I can probably live with it if it's necessary for synchronisation 😄  .

Just `ios` version still acts weirdly. If I open picker for second time, animation goes to 100% then freezes for about second and then continues as expected.

arrow freeze

Comment (jvaclavik) [reply packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js]: OK, should be fixed. Animation start is now wrapped in `InteractionManager.runAfterInteractions`

Comment (JoseDuSV) [reply packages/universal-components/src/RangeDatePicker/AnimatedDayItemArrow.js]: Looks good now! Thanks
